# Generated by Django 3.1.3 on 2020-11-04 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201104_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='introduction',
            name='Product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='channel',
            name='url',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='process_url',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='theme_url',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='work_url',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='titlecover',
            name='cover_url',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='titlecover',
            name='thumbnail_url',
            field=models.URLField(max_length=2000),
        ),
    ]
