# Generated by Django 3.1.3 on 2020-11-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_review_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.URLField(max_length=2000, null=True),
        ),
    ]
