# Generated by Django 3.1.3 on 2020-11-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_post_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image_url',
            field=models.URLField(max_length=2000, null=True),
        ),
    ]
