# Generated by Django 3.1.3 on 2020-11-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201104_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cheer_point',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
