# Generated by Django 3.1.3 on 2020-11-06 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_review_created_at'),
        ('user', '0004_auto_20201105_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'social_platforms',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='social_login_id',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.coupon')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'user_coupons',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='coupon',
            field=models.ManyToManyField(related_name='user', through='user.UserCoupon', to='product.Coupon'),
        ),
        migrations.AddField(
            model_name='user',
            name='social',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.socialplatform'),
        ),
    ]
