# Generated by Django 3.1.3 on 2020-11-06 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20201106_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercoupon',
            old_name='coupon_id',
            new_name='coupon',
        ),
        migrations.RenameField(
            model_name='usercoupon',
            old_name='user_id',
            new_name='user',
        ),
    ]
